### ISSUE TITLE
Bonito step running time

### ISSUE THREAD

**Issue by dweemx** [scottdbrown/minion-plasmid-consensus#1]
I'm trying to run the `bonito_duplex` step:

```
bonito \
   duplex \
   --pairs pseudopairs.txt \
   --max-cpus 1 \
   --device cuda:0 \
   dna_r10.3 \
   fast5_dir \
   > duplex.fasta
```

In my case, I tried to run it with 780 pairs using `Bonito v0.4.0a`. I used the following GPU card: NVIDIA Corporation TU104GL [Tesla T4] (1 GPU, 64 cores, 256 Gb RAM). It did not finish after 3h.

Any idea why this taking so long compared to what you stated in the paper: "On average, Bonito duplex base calling jobs of around 750 read pairs took 20 minutes to complete." ?

**Comment by scottdbrown** [comment]
Hi there,
That card does appear less powerful compared to the RTX 3090 I was using (3090 has 24GB VRAM, 10496 CUDA cores while the T4 has 16GB VRAM and 2560 CUDA cores), so that may be part of the explanation. 
Does `nvidia-smi` or `gpustat` show that the card is active? I did have random cases where a run would just get stuck for some reason (and the GPU would be idle), and I would have to restart it (though I was running on a GPU cluster, and getting stuck seemed to coincide with high usage by other users - I suspect that `bonito` is resource-hungry).

**Comment by dweemx** [comment]
Hi, thanks for your input.
It turned out `--max-cpu 1` was the issue

**Comment by scottdbrown** [comment]
Interesting - did you remove that or increase it?
